image = "redis"

[env]

[[services]]
http_checks   = []
internal_port = 6379
processes     = [ "app" ]
protocol      = "tcp"
script_checks = []

  [services.concurrency]
  hard_limit = 500
  soft_limit = 250
  type       = "requests"

  [[services.ports]]
  handlers = [ "http" ]
  port     = 6379

  [[services.tcp_checks]]
  grace_period  = "1s"
  interval      = "15s"
  restart_limit = 6
  timeout       = "2s"

[launcher]
name = "Redis"
description = "Redis is an in-memory data structure store, used as a distributed, in-memory key–value database, cache and message broker, with optional durability."
logo_url = "https://github.com/lubien/redis-launcher/raw/main/redis.png"
post_instructions = "Your new Livebook app is ready to go"
template_description = "This template will deploy a Livebook VM with an attached persistent volume."
